### ISSUE TITLE
Spelling errors in README.md

### ISSUE THREAD

**Issue by urpwnd** [Foxfyre/coyote-and-crow#15]
**_ALL CAPS_** showing them below! Last one, probably meant to be "diverse"?

More than 700 years ago, a massive disaster changed the course of history. The world was plunged into centuries of darkness, but the event also introduced the Adanadi - The Gift- a strange mark that appeared on all life. This mark would have a massive impact on **_HUMANITYH. CENTURERS_** later, the Earth is healing. New, advanced nations have risen. Ancient legends stir.

Coyote & Crow is a tabletop roleplaying game set in an alternate future where colonization of the Americas never happened. In this world that is both familiar and entirely new, you'll take on the role of heroic characters adventuring in a changing landscape.

Coyote & Crow is a bold look **_IINTO_** a different future full of possibilities and fresh perspectives, created and developed by a **_DIVER_**, Indigenous-led team.

**Comment by Foxfyre** [comment]
Fixed in 1.0.1
